spring.application.name=notification_service_airbnb

server.port=8081

#for email notifiation 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awadhviraj612@gmail.com
spring.mail.password=xnqi dutm vpkc xilb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#For sms using twilio
twilio.account.sid=ACxxxxxxxxx
twilio.auth.token=XXXXXXXXXXX
twilio.phone.number=+14452754155

